import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import HeroSection from '@/Components/HeroSection'
import FirstAlignerFree from '@/Components/FirstAlignerFree'
import WhyLeo from './WhyLeo'
import VideoSection from './VideoSection'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
      <HeroSection />
      <FirstAlignerFree />
      <WhyLeo />
      <VideoSection />
      </>
    </>
  )
}
